// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

// import { defineConfig } from 'prisma/config'
// import * as dotenv from 'dotenv'
// import * as path from 'path'

// dotenv.config({ path: path.join(__dirname, '../.env') })

// export default defineConfig({
//   earlyAccess: true,
//   schema: path.join(__dirname, 'schema.prisma'),
//   datasource: {
//     url: process.env.DATABASE_URL!,
//   },
// })


// prisma/prisma.config.ts

import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "./schema.prisma",

  migrations: {
    path: "./migrations",
  },

  datasource: {
    url: process.env.DATABASE_URL!,
  },
});
